### ISSUE TITLE
Figure out whether opencanary-correlator is needed

### ISSUE THREAD

**Issue by webknjaz** [patron-it/opencanary#10]
* https://github.com/thinkst/opencanary-correlator
* Might be useful for #3

**Comment by martin-haller** [comment]
No, we will not need correlator, as we will manage the logs ourself (custom log backend server).

**Comment by webknjaz** [comment]
There's some leftover scripts in this project referring to that. I think I'll just remove those then.

**Comment by martin-haller** [comment]
Yes, no problem.
