### ISSUE TITLE
Merging changes from upstream and other forks

### ISSUE THREAD

**Issue by webknjaz** [patron-it/opencanary#12]
I was merging new code from across whole fork network in the beginning. So that this repo tree contained the most up-to-date code.

Now, there's `chriswhitehat/opencanary:master` `chriswhitehat/opencanary:scapy` and `thinkst/opencanary:master`, which contain conflicting changes (mostly because I rewrote CLI and refactored bits of code to support Python 3, not only Python 2.

So what do we do with this? Do we need those changes merged into our fork? It looks like there's about 5 modules added and up-to-date docs committed to the upstream.

**Comment by webknjaz** [comment]
@Patrhal ^

**Comment by webknjaz** [comment]
So what do you think about this?

**Comment by martin-haller** [comment]
@webknjaz right now I would prefer to finish the deployment and automation process. Than we can come back to this topic :)
