### ISSUE TITLE
Tarpitting implementation

### ISSUE THREAD

**Issue by webknjaz** [patron-it/opencanary#5]
Smth like delaying next password prompts upon unsuccessful attempts.

**Comment by webknjaz** [comment]
@Patrhal it looks like it needs to be done on per-module basis. What are the most important modules I need to look at first?

**Comment by martin-haller** [comment]
@webknjaz Currently it is SSH.

**Comment by webknjaz** [comment]
Okay, I'll start with that

**Comment by webknjaz** [comment]
So I've managed to implement this dummy delay, which postpones auth prompt for 30 seconds if the previous attempt from the same host was less than 3 seconds before that.

**Comment by webknjaz** [comment]
Oh, and that's released as `v0.7.0`

**Comment by webknjaz** [comment]
Let's stop at ssh and return to this if it'll be needed for other services.
