### ISSUE TITLE
Implement deployment to PYPI and sourcing version from tag

### ISSUE THREAD

**Issue by webknjaz** [patron-it/opencanary#9]
After #8

**Comment by webknjaz** [comment]
@Patrhal since opencanary name is already taken on PyPI (https://pypi.org/p/opencanary) we need a new name. Maybe the same, but with prefix? patron-it-opencanary? Maybe something shorter? Any ideas?

**Comment by martin-haller** [comment]
I think that your proposal "patron-it-opencanary" could be fine. We can change it in a future if it will be necessary. Thanks :)

**Comment by webknjaz** [comment]
Still open, because of odd travis pass encryption

**Comment by webknjaz** [comment]
Ref https://github.com/travis-ci/dpl/issues/377
